# Vectorisation

In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [24]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorised time: " +str(1000*(toc-tic))+" ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("For loop time: " +str(1000*(toc-tic))+" ms")

250137.5766206209
Vectorised time: 2.145051956176758 ms
250137.57662062117
For loop time: 560.3888034820557 ms


In [25]:
a = np.random.randn(4, 3)
b = np.random.randn(3, 2) 
c = a * b


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [28]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a * b
print(a)
print(b)
print(c)

[[ 0.26924553 -0.59818172  0.46470982]
 [-0.13660596 -0.08584731  1.30426148]
 [-1.05061265 -0.43781345  0.14689489]]
[[ 1.27975116]
 [-0.26750762]
 [ 0.74916899]]
[[ 0.34456728 -0.76552375  0.59471293]
 [ 0.03654314  0.02296481 -0.34889989]
 [-0.78708642 -0.32799626  0.11004909]]
